# add stages here 
stages:
  stage_01_get_data:
    cmd: python src/stage_01_get_data.py --config_path=configs/config.yaml
    deps:
    - src/stage_01_get_data.py
    - src/utils/common_utils.py
    - configs/config.yaml
    outs:
    - data/ants
    - data/beetle
    - data/bees
    - data/catterpillar
    - data/earthworms
    - data/earwig
    - data/grasshopper
    - data/slug
    - data/moth
    - data/snail
    - data/wasp
    - data/weevil
  stage_02_prepare_base_model:
    cmd: python src/stage_02_prepare_base_model.py --config_path=configs/config.yaml --params_path=params.yaml
    deps:
    - src/stage_02_prepare_base_model.py
    - src/utils/common_utils.py
    - configs/config.yaml
    - src/utils/model.py
    - params.yaml
    outs:
    - artifacts/base_model/updated_base_model.h5
  stage_03_prepare_callback:
    cmd: python src/stage_03_prepare_callback.py --config_path=configs/config.yaml
    deps:
    - src/stage_03_prepare_callback.py
    - src/utils/common_utils.py
    - configs/config.yaml
    - src/utils/call_backs.py
    outs:
    - artifacts/callbacks/tensorboard.pkl
    - artifacts/callbacks/model_checkpoint.h5
    - artifacts/callbacks/early_stopping.pkl